apiVersion: apps/v1
kind: Deployment
metadata: 
  name: todo-add
spec:
  replicas: 2
  selector:
    matchLabels:
      app: add-task
  template:
    metadata:
      labels: 
        app: add-task
    spec:
      containers:
        - image: rk8sacr.azurecr.io/todo-add-tasks-api:v1
          name: todo-app
          ports:
            - containerPort: 8000
          environment:
            - name: CONNECTION STRING
              value: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:devdas-sql-server.database.windows.net,1433;Database=dev-01-sqldb;Uid=devops123;Pwd=Devops@1@3#5;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;" 
            
